management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - info
logging:
  level:
    one.stand.mapper: debug
  file: logs/${spring.application.name}.log
