spring:
  redis:
    database: 0
    host: 124.71.46.105
    port: 6379
    password: redis123456
    timeout: 1000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1